#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $AURAX_REPO == "AuraXBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0F1cmFYTmV0d29yay9BdXJhWFVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $AURAX_REPO == "AuraXBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0F1cmFYTmV0d29yay9BdXJhWFVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $AURAX_REPO =~ $regex ]]
    then
        if [[ $AURAX_REPO_BRANCH ]]
        then
            echo "${AURAX_REPO}/archive/${AURAX_REPO_BRANCH}.zip"
        else
            echo "${AURAX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0F1cmFYTmV0d29yay9BdXJhWFVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="AuraXBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    AURAXPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $AURAXPATH
    echo "    Starting AuraXBot    "
    echo "
    ┏━━━┓          ┏┓    ┏┓
    ┃┏━┓┃          ┃┃   ┏┛┗┓
    ┃┃ ┃┣┓┏┳━┳━━┳┓┏┫┗━┳━┻┓┏┛
    ┃┗━┛┃┃┃┃┏┫┏┓┣╋╋┫┏┓┃┏┓┃┃
    ┃┏━┓┃┗┛┃┃┃┏┓┣╋╋┫┗┛┃┗┛┃┗┓
    ┗┛ ┗┻━━┻┛┗┛┗┻┛┗┻━━┻━━┻━┛  

    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
